services:
  - type: web
    name: dashboard-ufpr
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
